SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS user_comment;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS user_thread;
DROP TABLE IF EXISTS thread;
DROP TABLE IF EXISTS thread_category;
DROP TABLE IF EXISTS user;

SET FOREIGN_KEY_CHECKS = 1;