SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS daily_cart_activity;
DROP TABLE IF EXISTS daily_cart_food;
DROP TABLE IF EXISTS daily_cart;

DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS activity_category;

DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS food_category;

DROP TABLE IF EXISTS user;

SET FOREIGN_KEY_CHECKS = 1;